# Generated by Django 4.1.7 on 2023-02-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('desc', models.TextField(default='Описание товара', max_length=3000, null=True, verbose_name='Описание')),
                ('img_link', models.TextField(max_length=3000, verbose_name='Ссылка на изображения')),
                ('category_name', models.CharField(choices=[('Games', 'Игры'), ('Health', 'Здоровье'), ('Sport', 'Спорт'), ('Beauty', 'Красота'), ('Other', 'Разное')], default='Other', max_length=100, verbose_name='Категория')),
                ('residue', models.PositiveIntegerField(verbose_name='Остаток')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='удалено')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='Дата и время удаления')),
            ],
        ),
    ]
