# Generated by Django 4.1.7 on 2023-02-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='residue',
            field=models.PositiveIntegerField(null=True, verbose_name='Остаток'),
        ),
    ]
