# Generated by Django 4.1.7 on 2023-03-17 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0004_basket_product_product_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket_product',
            name='in_basket',
            field=models.BooleanField(default=True, verbose_name='В корзине'),
        ),
    ]
