# Generated by Django 4.1.7 on 2023-03-17 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0005_alter_basket_product_in_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket_product',
            name='amount',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
    ]
